name: "Check"
description: "Greet someone"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "22.0.0"
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ vars.NODE_VERSION }}
    - name: Install
      run: npm install
      shell: bash
    - name: Unit Test
      run: npm run test
      shell: bash
    - name: Run Lint
      run: npm run lint
      shell: bash
