name: CD workflow

on:
  push:
    branches:
      - develop

jobs:
  cd:
    runs-on: ubuntu-latest
    name: Build and publish docker
    steps:
      - uses: actions/checkout@v5
      - name: Login docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin
      - name: Build image docker
        run: docker build . -t doanxuanduyen/training:${{ github.sha }}
      - name: Push image docker
        run: docker push doanxuanduyen/training:${{ github.sha }}
