name: image-publish-workflow

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: doanxuanduyen/ci-cd-training/.github/quality@v4
      - uses: actions/checkout@v5
      - name: Login docker
        run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker
        run: docker build . -t doanxuanduyen/training:${{ github.sha }}
      - name: Docker push
        run: docker push doanxuanduyen/training:${{ github.sha }}
